question_data_1 = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take "
             "it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state "
             "funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_2 = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science & Nature",
     "text": "Male pandas do handstands while urinating on trees. ",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "text": "The shotgun appears in every numbered Resident Evil game.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "text": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Cartoon & Animations",
     "text": "Nickelodeon rejected the pilot to Adventure Time.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "History",
     "text": "Franz Joseph I was the last emperor of Austria.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Vehicles",
     "text": "The majority of Subaru vehicles are made in China.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime & Manga",
     "text": "In Chobits, Hideki found Chii in his apartment.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "text": "Haggis is traditionally ate on Burns Night.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "History",
     "text": "Augustus was the cousin of Julius Caesar.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "hard",
     "category": "General Knowledge",
     "text": "This is the correct spelling of 'Supercalifragilisticexpialidocious'.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "text": "In Portal, the Companion Cube's ARE sentient.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "text": "The ghosts in 'Pac - Man' and 'Ms.Pac - Man' have completely different behavior.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "text": "In 'Sonic Adventure', you are able to transform into Super Sonic at will after completing "
                 "the main story.",
     "answer":"False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime & Manga",
     "text": "The anime 'Lucky Star' follows the story of one girl who is unaware she is God.",
     "answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "text": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by "
                 "stuffing a chicken with snow.",
     "answer": "True",
     "incorrect_answers": ["False"]}
]
